### ISSUE TITLE
xsd version of the dtd

### ISSUE THREAD

**Issue by alegorico** [mybatis/mybatis.github.io#12]
It would be interesting to have an XSD version of There DTD mapper

there are plans for this idea?

**Comment by hazendaz** [comment]
believe this is what you are after https://github.com/mybatis/mybatis-3/tree/master/src/main/resources/org/apache/ibatis/builder/xml ?  XSD already exists for the dtd mapper as well as config.

**Comment by hazendaz** [comment]
closing as item exists.
