### ISSUE TITLE
http://blog.mybatis.org/ is not good in China

### ISSUE THREAD

**Issue by paulvi** [mybatis/mybatis.github.io#2]
FYI blogger.com is blocked in China

![blogger-com-in-china](https://f.cloud.github.com/assets/1614482/839389/05a06304-f343-11e2-9163-54ec0a3e8004.PNG)

Have you considered have blog on GitHub pages or other hosting ?

**Comment by hazendaz** [comment]
closing as this all appears ok for a very long time.  All sites listed redirect to current one or have links to get there (ie from ibatis).
